# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraint.xdc

# Block Designs: bd/ctrl_storage/ctrl_storage.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ctrl_storage || ORIG_REF_NAME==ctrl_storage} -quiet] -quiet

# IP: bd/ctrl_storage/ip/ctrl_storage_axi_dma_0_0/ctrl_storage_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ctrl_storage_axi_dma_0_0 || ORIG_REF_NAME==ctrl_storage_axi_dma_0_0} -quiet] -quiet

# IP: bd/ctrl_storage/ip/ctrl_storage_axis_data_fifo_0_0/ctrl_storage_axis_data_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ctrl_storage_axis_data_fifo_0_0 || ORIG_REF_NAME==ctrl_storage_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/ctrl_storage/ip/ctrl_storage_processing_system7_0_0/ctrl_storage_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ctrl_storage_processing_system7_0_0 || ORIG_REF_NAME==ctrl_storage_processing_system7_0_0} -quiet] -quiet

# IP: bd/ctrl_storage/ip/ctrl_storage_axi_gpio_0_0/ctrl_storage_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ctrl_storage_axi_gpio_0_0 || ORIG_REF_NAME==ctrl_storage_axi_gpio_0_0} -quiet] -quiet

# IP: bd/ctrl_storage/ip/ctrl_storage_xlconcat_0_0/ctrl_storage_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ctrl_storage_xlconcat_0_0 || ORIG_REF_NAME==ctrl_storage_xlconcat_0_0} -quiet] -quiet

# IP: bd/ctrl_storage/ip/ctrl_storage_axi_intc_0_0/ctrl_storage_axi_intc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ctrl_storage_axi_intc_0_0 || ORIG_REF_NAME==ctrl_storage_axi_intc_0_0} -quiet] -quiet

# IP: bd/ctrl_storage/ip/ctrl_storage_xbar_0/ctrl_storage_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ctrl_storage_xbar_0 || ORIG_REF_NAME==ctrl_storage_xbar_0} -quiet] -quiet

# IP: bd/ctrl_storage/ip/ctrl_storage_ps7_0_axi_periph_0/ctrl_storage_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ctrl_storage_ps7_0_axi_periph_0 || ORIG_REF_NAME==ctrl_storage_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/ctrl_storage/ip/ctrl_storage_rst_ps7_0_5M_0/ctrl_storage_rst_ps7_0_5M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ctrl_storage_rst_ps7_0_5M_0 || ORIG_REF_NAME==ctrl_storage_rst_ps7_0_5M_0} -quiet] -quiet

# IP: bd/ctrl_storage/ip/ctrl_storage_axi_mem_intercon_1/ctrl_storage_axi_mem_intercon_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ctrl_storage_axi_mem_intercon_1 || ORIG_REF_NAME==ctrl_storage_axi_mem_intercon_1} -quiet] -quiet

# IP: bd/ctrl_storage/ip/ctrl_storage_axi_gpio_1_0/ctrl_storage_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ctrl_storage_axi_gpio_1_0 || ORIG_REF_NAME==ctrl_storage_axi_gpio_1_0} -quiet] -quiet

# IP: bd/ctrl_storage/ip/ctrl_storage_axi_gpio_1_1/ctrl_storage_axi_gpio_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ctrl_storage_axi_gpio_1_1 || ORIG_REF_NAME==ctrl_storage_axi_gpio_1_1} -quiet] -quiet

# IP: bd/ctrl_storage/ip/ctrl_storage_freq_div_0_0/ctrl_storage_freq_div_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ctrl_storage_freq_div_0_0 || ORIG_REF_NAME==ctrl_storage_freq_div_0_0} -quiet] -quiet

# IP: bd/ctrl_storage/ip/ctrl_storage_axi_gpio_2_0/ctrl_storage_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ctrl_storage_axi_gpio_2_0 || ORIG_REF_NAME==ctrl_storage_axi_gpio_2_0} -quiet] -quiet

# IP: bd/ctrl_storage/ip/ctrl_storage_axi_gpio_3_0/ctrl_storage_axi_gpio_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ctrl_storage_axi_gpio_3_0 || ORIG_REF_NAME==ctrl_storage_axi_gpio_3_0} -quiet] -quiet

# IP: bd/ctrl_storage/ip/ctrl_storage_axi_gpio_3_1/ctrl_storage_axi_gpio_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ctrl_storage_axi_gpio_3_1 || ORIG_REF_NAME==ctrl_storage_axi_gpio_3_1} -quiet] -quiet

# IP: bd/ctrl_storage/ip/ctrl_storage_axi_gpio_5_0/ctrl_storage_axi_gpio_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ctrl_storage_axi_gpio_5_0 || ORIG_REF_NAME==ctrl_storage_axi_gpio_5_0} -quiet] -quiet

# IP: bd/ctrl_storage/ip/ctrl_storage_axi_gpio_5_1/ctrl_storage_axi_gpio_5_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ctrl_storage_axi_gpio_5_1 || ORIG_REF_NAME==ctrl_storage_axi_gpio_5_1} -quiet] -quiet

# IP: bd/ctrl_storage/ip/ctrl_storage_axi_gpio_7_0/ctrl_storage_axi_gpio_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ctrl_storage_axi_gpio_7_0 || ORIG_REF_NAME==ctrl_storage_axi_gpio_7_0} -quiet] -quiet

# IP: bd/ctrl_storage/ip/ctrl_storage_util_vector_logic_0_0/ctrl_storage_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ctrl_storage_util_vector_logic_0_0 || ORIG_REF_NAME==ctrl_storage_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/ctrl_storage/ip/ctrl_storage_util_vector_logic_0_1/ctrl_storage_util_vector_logic_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ctrl_storage_util_vector_logic_0_1 || ORIG_REF_NAME==ctrl_storage_util_vector_logic_0_1} -quiet] -quiet

# IP: bd/ctrl_storage/ip/ctrl_storage_xlconstant_0_0/ctrl_storage_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ctrl_storage_xlconstant_0_0 || ORIG_REF_NAME==ctrl_storage_xlconstant_0_0} -quiet] -quiet

# IP: bd/ctrl_storage/ip/ctrl_storage_system_ila_0_1/ctrl_storage_system_ila_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ctrl_storage_system_ila_0_1 || ORIG_REF_NAME==ctrl_storage_system_ila_0_1} -quiet] -quiet

# IP: bd/ctrl_storage/ip/ctrl_storage_xlconcat_2_0/ctrl_storage_xlconcat_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ctrl_storage_xlconcat_2_0 || ORIG_REF_NAME==ctrl_storage_xlconcat_2_0} -quiet] -quiet

# IP: bd/ctrl_storage/ip/ctrl_storage_pretender_1_0/ctrl_storage_pretender_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ctrl_storage_pretender_1_0 || ORIG_REF_NAME==ctrl_storage_pretender_1_0} -quiet] -quiet

# IP: bd/ctrl_storage/ip/ctrl_storage_auto_pc_0/ctrl_storage_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ctrl_storage_auto_pc_0 || ORIG_REF_NAME==ctrl_storage_auto_pc_0} -quiet] -quiet

# IP: bd/ctrl_storage/ip/ctrl_storage_auto_pc_1/ctrl_storage_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ctrl_storage_auto_pc_1 || ORIG_REF_NAME==ctrl_storage_auto_pc_1} -quiet] -quiet

# IP: bd/ctrl_storage/ip/ctrl_storage_auto_us_0/ctrl_storage_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ctrl_storage_auto_us_0 || ORIG_REF_NAME==ctrl_storage_auto_us_0} -quiet] -quiet

# IP: bd/ctrl_storage/ip/ctrl_storage_ctrl_mod2_0_0/ctrl_storage_ctrl_mod2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ctrl_storage_ctrl_mod2_0_0 || ORIG_REF_NAME==ctrl_storage_ctrl_mod2_0_0} -quiet] -quiet

# XDC: bd/ctrl_storage/ctrl_storage_ooc.xdc
