# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/special/pj5/pj5.srcs/sources_1/bd/ctrl_storage/ip/ctrl_storage_axis_data_fifo_0_0/ctrl_storage_axis_data_fifo_0_0.xci
# IP: The module: 'ctrl_storage_axis_data_fifo_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/special/pj5/pj5.srcs/sources_1/bd/ctrl_storage/ip/ctrl_storage_axis_data_fifo_0_0/ctrl_storage_axis_data_fifo_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ctrl_storage_axis_data_fifo_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/special/pj5/pj5.srcs/sources_1/bd/ctrl_storage/ip/ctrl_storage_axis_data_fifo_0_0/ctrl_storage_axis_data_fifo_0_0.xci
# IP: The module: 'ctrl_storage_axis_data_fifo_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/special/pj5/pj5.srcs/sources_1/bd/ctrl_storage/ip/ctrl_storage_axis_data_fifo_0_0/ctrl_storage_axis_data_fifo_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ctrl_storage_axis_data_fifo_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
