set_property -dict {PACKAGE_PIN W16 IOSTANDARD LVCMOS33} [get_ports rst_o]
set_property -dict {PACKAGE_PIN T15 IOSTANDARD LVCMOS33} [get_ports row_clk_o]
set_property -dict {PACKAGE_PIN Y16 IOSTANDARD LVCMOS33} [get_ports col_clk_o]
set_property -dict {PACKAGE_PIN U17 IOSTANDARD LVCMOS33} [get_ports row_sel_o]
set_property -dict {PACKAGE_PIN V18 IOSTANDARD LVCMOS33} [get_ports col_sel_o]
set_property -dict {PACKAGE_PIN R18 IOSTANDARD LVCMOS33} [get_ports c2_o]
set_property -dict {PACKAGE_PIN Y19 IOSTANDARD LVCMOS33} [get_ports c3_o]
set_property -dict {PACKAGE_PIN P16 IOSTANDARD LVCMOS33} [get_ports c4_o]
set_property -dict {PACKAGE_PIN W19 IOSTANDARD LVCMOS33} [get_ports sh1_o]
set_property -dict {PACKAGE_PIN R17 IOSTANDARD LVCMOS33} [get_ports sh2_o]
set_property -dict {PACKAGE_PIN V20 IOSTANDARD LVCMOS33} [get_ports amp2_en_o]
set_property -dict {PACKAGE_PIN N17 IOSTANDARD LVCMOS33} [get_ports pretender_data_o]
set_property -dict {PACKAGE_PIN N18 IOSTANDARD LVCMOS33} [get_ports trig_2_o]
set_property -dict {PACKAGE_PIN U20 IOSTANDARD LVCMOS33} [get_ports trig_3_o]
set_property -dict {PACKAGE_PIN M19 IOSTANDARD LVCMOS33} [get_ports trig_4_o]
set_property -dict {PACKAGE_PIN U19 IOSTANDARD LVCMOS33} [get_ports trig_5_o]

set_property -dict {PACKAGE_PIN U18 IOSTANDARD LVCMOS33} [get_ports clk_i]

set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN V15} [get_ports {vout_din[0]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN W14} [get_ports {vout_din[2]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN V12} [get_ports {vout_din[4]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN U14} [get_ports {vout_din[6]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN V13} [get_ports {vout_din[8]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN Y13} [get_ports adc_ch1_clk]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN W15} [get_ports {vout_din[1]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN Y14} [get_ports {vout_din[3]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN W13} [get_ports {vout_din[5]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN U15} [get_ports {vout_din[7]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN U13} [get_ports {vout_din[9]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN W11} [get_ports {adc_ch1_en_not}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN V11} [get_ports {vout_din[10]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN W10} [get_ports {vout_din[12]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN Y9} [get_ports {vout_din[14]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN Y7} [get_ports {vout_din[16]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN W6} [get_ports {vout_din[18]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN U9} [get_ports adc_ch2_clk]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN V10} [get_ports {vout_din[11]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN W9} [get_ports {vout_din[13]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN Y8} [get_ports {vout_din[15]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN Y6} [get_ports {vout_din[17]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN V6} [get_ports {vout_din[19]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN T9} [get_ports {adc_ch2_en_not}]





