#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : ctrl_storage.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Sun Mar 03 17:09:31 +0800 2024
# SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved. 
#
# usage: ctrl_storage.sh [-help]
# usage: ctrl_storage.sh [-lib_map_path]
# usage: ctrl_storage.sh [-noclean_files]
# usage: ctrl_storage.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'ctrl_storage.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xpm lib_pkg_v1_0_2 fifo_generator_v13_2_5 lib_fifo_v1_0_14 lib_srl_fifo_v1_0_2 lib_cdc_v1_0_2 axi_datamover_v5_1_22 axi_sg_v4_1_13 axi_dma_v7_1_21 xil_defaultlib axis_infrastructure_v1_1_0 axis_data_fifo_v2_0_2 axi_infrastructure_v1_1_0 axi_vip_v1_1_6 processing_system7_vip_v1_0_8 axi_lite_ipif_v3_0_4 interrupt_control_v3_1_4 axi_gpio_v2_0_22 xlconcat_v2_1_3 axi_intc_v4_1_14 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_20 axi_data_fifo_v2_1_19 axi_crossbar_v2_1_21 proc_sys_reset_v5_0_13 util_vector_logic_v2_0_1 xlconstant_v1_1_6 gigantic_mux axi_protocol_converter_v2_1_20 axi_clock_converter_v2_1_19 blk_mem_gen_v8_4_4 axi_dwidth_converter_v2_1_20)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "ctrl_storage.sh - Script generated by export_simulation (Vivado v2019.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/2d50/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ip/ctrl_storage_processing_system7_0_0" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8f82/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "D:/Xilinx/Vivado/2019.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "D:/Xilinx/Vivado/2019.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "D:/Xilinx/Vivado/2019.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "D:/Xilinx/Vivado/2019.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "D:/Xilinx/Vivado/2019.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "D:/Xilinx/Vivado/2019.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "D:/Xilinx/Vivado/2019.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "D:/Xilinx/Vivado/2019.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "D:/Xilinx/Vivado/2019.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/2d50/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ip/ctrl_storage_processing_system7_0_0" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8f82/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "D:/Xilinx/Vivado/2019.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "D:/Xilinx/Vivado/2019.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "D:/Xilinx/Vivado/2019.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "D:/Xilinx/Vivado/2019.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/2d50/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ip/ctrl_storage_processing_system7_0_0" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8f82/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/276e/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_5 $vhdlan_opts \
    "$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/276e/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/2d50/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ip/ctrl_storage_processing_system7_0_0" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8f82/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/276e/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_fifo_v1_0_14 $vhdlan_opts \
    "$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/a5cb/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_22 $vhdlan_opts \
    "$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/1e40/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_sg_v4_1_13 $vhdlan_opts \
    "$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/4919/hdl/axi_sg_v4_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_dma_v7_1_21 $vhdlan_opts \
    "$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/ec2a/hdl/axi_dma_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ctrl_storage/ip/ctrl_storage_axi_dma_0_0/sim/ctrl_storage_axi_dma_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axis_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/2d50/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ip/ctrl_storage_processing_system7_0_0" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8f82/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8713/hdl/axis_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_data_fifo_v2_0_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/2d50/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ip/ctrl_storage_processing_system7_0_0" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8f82/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/3341/hdl/axis_data_fifo_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/2d50/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ip/ctrl_storage_processing_system7_0_0" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8f82/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ctrl_storage/ip/ctrl_storage_axis_data_fifo_0_0/sim/ctrl_storage_axis_data_fifo_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/2d50/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ip/ctrl_storage_processing_system7_0_0" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8f82/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_6 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/2d50/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ip/ctrl_storage_processing_system7_0_0" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8f82/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/dc12/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_8 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/2d50/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ip/ctrl_storage_processing_system7_0_0" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8f82/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/2d50/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/2d50/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ip/ctrl_storage_processing_system7_0_0" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8f82/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ctrl_storage/ip/ctrl_storage_processing_system7_0_0/sim/ctrl_storage_processing_system7_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_22 $vhdlan_opts \
    "$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/f71e/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ctrl_storage/ip/ctrl_storage_axi_gpio_0_0/sim/ctrl_storage_axi_gpio_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconcat_v2_1_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/2d50/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ip/ctrl_storage_processing_system7_0_0" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8f82/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/442e/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/2d50/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ip/ctrl_storage_processing_system7_0_0" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8f82/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ctrl_storage/ip/ctrl_storage_xlconcat_0_0/sim/ctrl_storage_xlconcat_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_intc_v4_1_14 $vhdlan_opts \
    "$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/f78a/hdl/axi_intc_v4_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ctrl_storage/ip/ctrl_storage_axi_intc_0_0/sim/ctrl_storage_axi_intc_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/2d50/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ip/ctrl_storage_processing_system7_0_0" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8f82/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_20 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/2d50/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ip/ctrl_storage_processing_system7_0_0" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8f82/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/72d4/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_19 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/2d50/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ip/ctrl_storage_processing_system7_0_0" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8f82/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/60de/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/2d50/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ip/ctrl_storage_processing_system7_0_0" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8f82/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/6b0d/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/2d50/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ip/ctrl_storage_processing_system7_0_0" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8f82/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ctrl_storage/ip/ctrl_storage_xbar_0/sim/ctrl_storage_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ctrl_storage/ip/ctrl_storage_rst_ps7_0_5M_0/sim/ctrl_storage_rst_ps7_0_5M_0.vhd" \
    "$ref_dir/../../../bd/ctrl_storage/ip/ctrl_storage_axi_gpio_1_0/sim/ctrl_storage_axi_gpio_1_0.vhd" \
    "$ref_dir/../../../bd/ctrl_storage/ip/ctrl_storage_axi_gpio_1_1/sim/ctrl_storage_axi_gpio_1_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/2d50/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ip/ctrl_storage_processing_system7_0_0" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8f82/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ctrl_storage/sim/ctrl_storage.v" \
    "$ref_dir/../../../bd/ctrl_storage/ipshared/e66b/src/freq_div.v" \
    "$ref_dir/../../../bd/ctrl_storage/ip/ctrl_storage_freq_div_0_0/sim/ctrl_storage_freq_div_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ctrl_storage/ip/ctrl_storage_axi_gpio_2_0/sim/ctrl_storage_axi_gpio_2_0.vhd" \
    "$ref_dir/../../../bd/ctrl_storage/ip/ctrl_storage_axi_gpio_3_0/sim/ctrl_storage_axi_gpio_3_0.vhd" \
    "$ref_dir/../../../bd/ctrl_storage/ip/ctrl_storage_axi_gpio_3_1/sim/ctrl_storage_axi_gpio_3_1.vhd" \
    "$ref_dir/../../../bd/ctrl_storage/ip/ctrl_storage_axi_gpio_5_0/sim/ctrl_storage_axi_gpio_5_0.vhd" \
    "$ref_dir/../../../bd/ctrl_storage/ip/ctrl_storage_axi_gpio_5_1/sim/ctrl_storage_axi_gpio_5_1.vhd" \
    "$ref_dir/../../../bd/ctrl_storage/ip/ctrl_storage_axi_gpio_7_0/sim/ctrl_storage_axi_gpio_7_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work util_vector_logic_v2_0_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/2d50/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ip/ctrl_storage_processing_system7_0_0" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8f82/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/2137/hdl/util_vector_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/2d50/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ip/ctrl_storage_processing_system7_0_0" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8f82/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ctrl_storage/ip/ctrl_storage_util_vector_logic_0_0/sim/ctrl_storage_util_vector_logic_0_0.v" \
    "$ref_dir/../../../bd/ctrl_storage/ip/ctrl_storage_util_vector_logic_0_1/sim/ctrl_storage_util_vector_logic_0_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_6 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/2d50/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ip/ctrl_storage_processing_system7_0_0" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8f82/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/34f7/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/2d50/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ip/ctrl_storage_processing_system7_0_0" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8f82/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ctrl_storage/ip/ctrl_storage_xlconstant_0_0/sim/ctrl_storage_xlconstant_0_0.v" \
    "$ref_dir/../../../bd/ctrl_storage/ip/ctrl_storage_system_ila_0_1/bd_0/sim/bd_0105.v" \
    "$ref_dir/../../../bd/ctrl_storage/ip/ctrl_storage_system_ila_0_1/bd_0/ip/ip_0/sim/bd_0105_ila_lib_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work gigantic_mux $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/2d50/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ip/ctrl_storage_processing_system7_0_0" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8f82/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/d322/hdl/gigantic_mux_v1_0_cntr.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/2d50/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ip/ctrl_storage_processing_system7_0_0" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8f82/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ctrl_storage/ip/ctrl_storage_system_ila_0_1/bd_0/ip/ip_1/bd_0105_g_inst_0_gigantic_mux.v" \
    "$ref_dir/../../../bd/ctrl_storage/ip/ctrl_storage_system_ila_0_1/bd_0/ip/ip_1/sim/bd_0105_g_inst_0.v" \
    "$ref_dir/../../../bd/ctrl_storage/ip/ctrl_storage_system_ila_0_1/sim/ctrl_storage_system_ila_0_1.v" \
    "$ref_dir/../../../bd/ctrl_storage/ip/ctrl_storage_xlconcat_2_0/sim/ctrl_storage_xlconcat_2_0.v" \
    "$ref_dir/../../../bd/ctrl_storage/ipshared/aec1/src/pretender.v" \
    "$ref_dir/../../../bd/ctrl_storage/ip/ctrl_storage_pretender_1_0/sim/ctrl_storage_pretender_1_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_20 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/2d50/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ip/ctrl_storage_processing_system7_0_0" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8f82/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/c4a6/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/2d50/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ip/ctrl_storage_processing_system7_0_0" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8f82/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ctrl_storage/ip/ctrl_storage_auto_pc_0/sim/ctrl_storage_auto_pc_0.v" \
    "$ref_dir/../../../bd/ctrl_storage/ip/ctrl_storage_auto_pc_1/sim/ctrl_storage_auto_pc_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_19 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/2d50/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ip/ctrl_storage_processing_system7_0_0" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8f82/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/9e81/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_4_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/2d50/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ip/ctrl_storage_processing_system7_0_0" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8f82/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/2985/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_dwidth_converter_v2_1_20 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/2d50/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ip/ctrl_storage_processing_system7_0_0" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8f82/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/d394/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/2d50/hdl" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ip/ctrl_storage_processing_system7_0_0" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../pj5_temp.srcs/sources_1/bd/ctrl_storage/ipshared/8f82/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ctrl_storage/ip/ctrl_storage_auto_us_0/sim/ctrl_storage_auto_us_0.v" \
    "$ref_dir/../../../bd/ctrl_storage/ipshared/766c/src/ctrl_v4.v" \
    "$ref_dir/../../../bd/ctrl_storage/ip/ctrl_storage_ctrl_mod2_0_0/sim/ctrl_storage_ctrl_mod2_0_0.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.ctrl_storage xil_defaultlib.glbl -o ctrl_storage_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./ctrl_storage_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./ctrl_storage.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key ctrl_storage_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc ctrl_storage_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./ctrl_storage.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: ctrl_storage.sh [-help]\n\
Usage: ctrl_storage.sh [-lib_map_path]\n\
Usage: ctrl_storage.sh [-reset_run]\n\
Usage: ctrl_storage.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
